# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: xterm-256color

window:
  padding:
    x: 0
    y: 0

  # Window class (Linux/BSD only):
  class:
    # Application instance name
    instance: Alacritty
    # General application class
    general: Alacritty

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular

  # Point size of the font
  size: 11.5

colors:
  # Default colors
  primary:
    background: "0x000000"
    foreground: "0xB3B1AD"

  # Normal colors
  normal:
    black: "0x01060E"
    red: "0xEA6C73"
    green: "0x91B362"
    yellow: "0xF9AF4F"
    blue: "0x53BDFA"
    magenta: "0xFAE994"
    cyan: "0x90E1C6"
    white: "0xC7C7C7"

  # Bright colors
  bright:
    black: "0x686868"
    red: "0xF07178"
    green: "0xC2D94C"
    yellow: "0xFFB454"
    blue: "0x59C2FF"
    magenta: "0xFFEE99"
    cyan: "0x95E6CB"
    white: "0xFFFFFF"

background_opacity: 0.8
