name: conecta
root: ~/dev/granter/conecta/
windows:
  - frontend-editor:
      root: ~/dev/granter/conecta/conecta-frontend
      panes:
        - editor:
            - nix develop
            - nvim .
  - frontend-term:
      root: ~/dev/granter/conecta/conecta-frontend
      layout: even-horizontal
      panes:
        - yarn:
            - nix develop
            - yarn dev
        - git:
            - nix develop
            - git status
  - backend-editor:
      root: ~/dev/granter/conecta/conecta-backend/
      panes:
        - editor:
            - nix develop .#test
            - nvim .
  - backend-term:
      root: ~/dev/granter/conecta/conecta-backend/
      layout: even-horizontal
      panes:
        - phx_server:
            - nix develop
            - MIX_ENV=dev mix phx.server
        - git:
            - nix develop
            - git status
