name: dotfiles
root: ~/dotfiles/

windows:
  - editor:
      root: ~/dotfiles/
      panes:
        - nvim .
  - term:
      root: ~/dotfiles/
      layout: even-horizontal
      panes:
        - git status

