name: favu
root: ~/dev/granter/flowtify/

windows:
  - frontend-editor:
      root: ~/dev/granter/flowtify/frontend/flowtify-frontend
      panes:
        - nvim .
  - frontend-term:
      root: ~/dev/granter/flowtify/frontend/flowtify-frontend
      layout: even-horizontal
      panes:
        - yarn dev
        - git status
  - backend-editor:
      root: ~/dev/granter/flowtify/backend/flowtify-backend
      panes:
        - nvim .
  - backend-term:
      root: ~/dev/granter/flowtify/backend/flowtify-backend
      layout: even-horizontal
      panes:
        - phx_server:
            - MIX_ENV=dev mix phx.server
        - git status

