name: granter-tools
root: ~/dev/granter/granter_tools/
windows:
  - frontend-editor:
      root: ~/dev/granter/granter_tools
      panes:
        - nvim .
  - frontend-term:
      root: ~/dev/granter/granter_tools
      layout: even-horizontal
      panes:
        - pnpm:
            - nix develop
            - pnpm dev
        - git:
            - nix develop
            - git status
  - backend-editor:
      root: ~/dev/granter/flowtify/backend/flowtify-backend
      panes:
        - nvim .
  - backend-term:
      root: ~/dev/granter/flowtify/backend/flowtify-backend
      layout: even-horizontal
      panes:
        - phx_server:
            - MIX_ENV=dev mix phx.server
        - git status
