name: granter-vue-library
root: ~/dev/granter/granter-vue-library/
windows:
  - editor:
      root: ~/dev/granter/granter-vue-library/
      panes:
        - editor:
            - nix develop
            - nvim .
  - term:
      root: ~/dev/granter/granter-vue-library/
      layout: even-horizontal
      panes:
        - yarn:
            - nix develop
            - pnpm storybook
        - git:
            - nix develop
            - git status
