name: httpp
root: ~/dev/httpp/
windows:
  - editor:
      root: ~/dev/httpp/
      panes:
        - nvim .
  - term:
      root: ~/dev/httpp/
      layout: even-horizontal
      panes:
        - echo HTTPP
