name: conecta
root: ~/dev/granter/inova_defesa/
windows:
  - frontend-editor:
      root: ~/dev/granter/inova_defesa/frontend/inova-frontend
      panes:
        - nvim .
  - frontend-term:
      root: ~/dev/granter/inova_defesa/frontend/inova-frontend
      layout: even-horizontal
      panes:
        - yarn:
            - nix develop
            - yarn dev
        - git:
            - nix develop
            - git status
  - backend-editor:
      root: ~/dev/granter/inova_defesa/backend/inova-backend
      panes:
        - editor:
            - nix develop
            - nvim .
  - backend-term:
      root: ~/dev/granter/inova_defesa/backend/inova-backend
      layout: even-horizontal
      panes:
        - phx_server:
            - nix develop
            - MIX_ENV=dev mix phx.server
        - git:
            - nix develop
            - git status
