name: otter
root: ~/dev/granter/otter/
windows:
  - frontend-editor:
      root: ~/dev/granter/otter/frontend/otter/
      panes:
        - editor:
            - nix develop --command fish -c nvim .
  - frontend-term:
      root: ~/dev/granter/otter/frontend/otter/
      layout: even-horizontal
      panes:
        - server:
            - nix develop --command fish -c "pnpm dev"
        - misc:
            - nix develop
  - backend-editor:
      root: ~/dev/granter/otter/backend/otter/
      panes:
        - editor:
            - nix develop .#test --command fish -c nvim .
  - backend-term:
      root: ~/dev/granter/otter/backend/otter/
      layout: even-horizontal
      panes:
        - server:
            - nix develop --command fish -c "LOCAL_EMAIL=1 MIX_ENV=dev mix phx.server"
        - misc:
            - nix develop
  - project:
      root: ~/dev/granter/otter/backend/otter/
      layout: even-horizontal
      panes:
        - misc:
            - git status
