name: otter
root: ~/dev/granter/otter/
windows:
  - frontend-editor:
      root: ~/dev/granter/otter/frontend/otter/
      panes:
        - editor:
            - nix develop --command fish -c "nvim .; fish"
  - frontend-term:
      root: ~/dev/granter/otter/frontend/otter/
      layout: even-horizontal
      panes:
        - yarn:
            - nix develop --command fish -c "pnpm dev; fish"
        - git:
            - git status
  - backend-editor:
      root: ~/dev/granter/otter/backend/otter/
      panes:
        - editor:
            - nix develop .#test --command fish -c "nvim .; fish"
  - backend-term:
      root: ~/dev/granter/otter/backend/otter/
      layout: even-horizontal
      panes:
        - phx_server:
            - nix develop --command fish -c "LOCAL_EMAIL=1 MIX_ENV=dev mix phx.server; fish"
        - git:
            - git status
