name: otter
root: ~/dev/granter/otter/
windows:
  - frontend-editor:
      root: ~/dev/granter/otter/frontend/otter/
      panes:
        - editor:
            - nix develop
            - nvim .
  - frontend-term:
      root: ~/dev/granter/otter/frontend/otter/
      layout: even-horizontal
      panes:
        - yarn:
            - nix develop
            - yarn dev
        - git:
            - nix develop
            - git status
  - backend-editor:
      root: ~/dev/granter/otter/backend/otter/
      panes:
        - editor:
            - nix develop .#test
            - nvim .
  - backend-term:
      root: ~/dev/granter/otter/backend/otter/
      layout: even-horizontal
      panes:
        - phx_server:
            - nix develop
            - export LOCAL_EMAIL=1
            - MIX_ENV=dev mix phx.server
        - git:
            - nix develop
            - git status
