vim.lsp.set_log_level("debug")

Lsp = require("nvim.plugins.lsp.utils")
require("nvim.plugins.lsp.tsserver")
-- require("nvim.plugins.lsp.vuels")
require("nvim.plugins.lsp.volar")
require("nvim.plugins.lsp.sumneko_lua")
require("nvim.plugins.lsp.elixirls")
require("nvim.plugins.lsp.efm")
-- require("nvim.plugins.lsp.diagnosticsls")
require("nvim.plugins.lsp.hls")
require("nvim.plugins.lsp.cssls")
require("nvim.plugins.lsp.jsonls")
require("nvim.plugins.lsp.hdl_checker")
require("nvim.plugins.lsp.texlab")
