name: xmonad-guihig
version: 0.1.0
synopsis: xmonad setting
github: guihig/dotfiles
author: guihig
maintainer: guiih.ig@gmail.com
copyright: © guihig
license: MIT
dependencies:
- X11
- base
- xmonad
- xmonad-contrib
- containers
- filepath
- directory
library:
  source-dirs: src
executables:
  xmonad:
    main: xmonad-guihig.hs
    ghc-options:
      - -Wall
      - -fwarn-tabs
      - -no-keep-hi-files
      - -no-keep-o-files
      - -threaded
      - -O2
      - -with-rtsopts=-N4
    dependencies:
    - xmonad-guihig
