require("mason").setup()
require("mason-lspconfig").setup({
    ensure_installed = {
        "lua_ls",
        "dockerls",
        "elixirls",
        "hls",
        "jsonls",
        "tsserver",
        "texlab",
        "pyright",
        "sqlls",
        "tailwindcss",
        "volar",
        "efm",
        "yamlls",
        "rust_analyzer",
        "clangd"
    }
})
