version: 2
root-markers:
  - .git/
lint-debounce: 1s
commands:
  - command: notepad
    arguments:
      - ${INPUT}
    title: メモ帳

tools:
  yarn-eslint: &yarn-eslint
    lint-command: 'yarn eslint -f unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"

  credo: &credo
    lint-command: "mix credo suggest --format=flycheck --read-from-stdin ${INPUT}"
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %t: %m'
      - '%f:%l: %t: %m'
    root-markers:
      - mix.lock
      - mix.exs

languages:
  javascript:
    - <<: *yarn-eslint

  typescript:
    - <<: *yarn-eslint

  typescriptreact:
    - <<: *yarn-eslint

  javascriptreact:
    - <<: *yarn-eslint

  vue:
    - <<: *yarn-eslint

  elixir:
    - <<: *credo
