require('nvim.core.options')
require('nvim.core.keybinds')
require('nvim.core.variables')
require('nvim.core.commands')
require('nvim.core.autocmds')
require('nvim.core.colorschemes')
require('nvim.core.highlights')
