local USER = vim.fn.expand("$USER")

Option.g({
    mouse = "a",
    encoding = "UTF-8",
    pastetoggle = "<F3>",
    hidden = true,
    timeoutlen = 1000,
    ttimeoutlen = 0,
    relativenumber = true,
    errorbells = false,
    tabstop = 4,
    softtabstop = 2,
    shiftwidth = 2,
    expandtab = true,
    smartindent = true,
    nu = true,
    wrap = false,
    smartcase = true,
    swapfile = false,
    backup = false,
    writebackup = false,
    undodir = "/home/" .. USER .. "/.vim/undodir",
    undofile = true,
    incsearch = true,
    showmode = false,
    completeopt = "menuone,noselect",
    shortmess = vim.o.shortmess .. 'c',
    cmdheight = 2,
    updatetime = 50,
    scrolloff = 8,
    termguicolors = true,
    signcolumn = "yes:1",
    foldlevelstart = 20,
    background = "dark"
})
